export const triviaData =[
  {
    level: 1,
    question: '¿Cuál es la capital de Francia?',
    answers: ['Roma', 'París', 'Londres', 'Madrid'],
    correctAnswer: 'París',
  },
  {
    level: 1,
    question: '¿Cuál es el océano más grande del mundo?',
    answers: ['Atlántico', 'Índico', 'Pacífico', 'Ártico'],
    correctAnswer: 'Pacífico',
  },
  {
    level: 1,
    question: '¿Cuál es el país más grande del mundo?',
    answers: ['Canadá', 'China', 'Rusia', 'Estados Unidos'],
    correctAnswer: 'Rusia',
  },
  {
    level: 1,
    question: '¿Cuál es el río más largo de Europa?',
    answers: ['Volga', 'Danubio', 'Rin', 'Loira'],
    correctAnswer: 'Volga',
  },
  {
    level: 1,
    question: '¿Cuál es el continente más grande del mundo?',
    answers: ['Asia', 'África', 'América', 'Europa'],
    correctAnswer: 'Asia',
  },
  {
    level: 1,
    question: '¿Cuál es el país más grande de América del Sur?',
    answers: ['Brasil', 'Argentina', 'Colombia', 'Perú'],
    correctAnswer: 'Brasil',
  },
  {
    level: 1,
    question: '¿Cuál es el animal terrestre más grande del mundo?',
    answers: ['Elefante', 'Jirafa', 'Hipopótamo', 'Rinoceronte'],
    correctAnswer: 'Elefante',
  },
  {
    level: 1,
    question: '¿Cuál es el océano más pequeño del mundo?',
    answers: ['Ártico', 'Índico', 'Atlántico', 'Pacífico'],
    correctAnswer: 'Ártico',
  },
  {
    level: 1,
    question: '¿Cuál es el país más visitado del mundo?',
    answers: ['Francia', 'España', 'Italia', 'Estados Unidos'],
    correctAnswer: 'Francia',
  },
  {
    level: 1,
    question: '¿Cuál es el lago más profundo del mundo?',
    answers: ['Baikal', 'Superior', 'Victoria', 'Tanganica'],
    correctAnswer: 'Baikal',
  },
  {
    level: 1,
    question: '¿Cuál es el país más pequeño de América?',
    answers: [
      'San Cristóbal y Nieves',
      'Antigua y Barbuda',
      'Barbados',
      'Granada',
    ],
    correctAnswer: 'San Cristóbal y Nieves',
  },
  {
    level: 1,
    question: '¿Cuál es el continente con más países?',
    answers: ['África', 'Asia', 'Europa', 'América'],
    correctAnswer: 'África',
  },
  {
    level: 1,
    question: '¿Cuál es el país más poblado de Europa?',
    answers: ['Rusia', 'Alemania', 'Francia', 'Reino Unido'],
    correctAnswer: 'Rusia',
  },
  {
    level: 1,
    question: '¿Cuál es el río más largo de América?',
    answers: ['Amazonas', 'Misisipi', 'Yukón', 'Paraná'],
    correctAnswer: 'Amazonas',
  },
  {
    level: 1,
    question: '¿Cuál es el continente donde se encuentra Egipto?',
    answers: ['Asia', 'África', 'Europa', 'Oceanía'],
    correctAnswer: 'África',
  },
  {
    level: 2,
    question: '¿Cuál es el país más grande de América del Norte?',
    answers: ['Estados Unidos', 'Canadá', 'México', 'Cuba'],
    correctAnswer: 'Canadá',
  },
  {
    level: 2,
    question: '¿Cuál es el lago más grande de América del Norte?',
    answers: ['Superior', 'Michigan', 'Huron', 'Erie'],
    correctAnswer: 'Superior',
  },
  {
    level: 2,
    question: '¿Cuál es el país más poblado de América del Sur?',
    answers: ['Brasil', 'Argentina', 'Colombia', 'Perú'],
    correctAnswer: 'Brasil',
  },
  {
    level: 2,
    question: '¿Cuál es el río más largo de América del Sur?',
    answers: ['Amazonas', 'Paraná', 'Orinoco', 'Magdalena'],
    correctAnswer: 'Amazonas',
  },
  {
    level: 2,
    question: '¿Cuál es el país más visitado de América del Norte?',
    answers: ['Estados Unidos', 'Canadá', 'México', 'Cuba'],
    correctAnswer: 'Estados Unidos',
  },
  {
    level: 2,
    question: '¿Cuál es el país más pequeño de Europa?',
    answers: ['Vaticano', 'Mónaco', 'San Marino', 'Liechtenstein'],
    correctAnswer: 'Vaticano',
  },
  {
    level: 2,
    question: '¿Cuál es el país más poblado de África?',
    answers: ['Nigeria', 'Etiopía', 'Egipto', 'Sudáfrica'],
    correctAnswer: 'Nigeria',
  },
  {
    level: 2,
    question: '¿Cuál es el país más grande de Oceanía?',
    answers: ['Australia', 'Nueva Zelanda', 'Papúa Nueva Guinea', 'Fiyi'],
    correctAnswer: 'Australia',
  },
  {
    level: 2,
    question: '¿Cuál es el río más largo de Asia?',
    answers: ['Yangtsé', 'Misisipi', 'Ganges', 'Amur'],
    correctAnswer: 'Yangtsé',
  },
  {
    level: 2,
    question: '¿Cuál es el país más poblado del mundo?',
    answers: ['India', 'China', 'Estados Unidos', 'Indonesia'],
    correctAnswer: 'China',
  },
  {
    level: 2,
    question: '¿Cuál es la montaña más alta del mundo?',
    answers: ['K2', 'Everest', 'Kangchenjunga', 'Lhotse'],
    correctAnswer: 'Everest',
  },
  {
    level: 2,
    question: '¿Cuál es el lago más alto del mundo?',
    answers: ['Titicaca', 'Baikal', 'Maracaibo', 'Vostok'],
    correctAnswer: 'Titicaca',
  },
  {
    level: 2,
    question: '¿Cuál es el país con más islas del mundo?',
    answers: ['Filipinas', 'Indonesia', 'Japón', 'Reino Unido'],
    correctAnswer: 'Indonesia',
  },
  {
    level: 2,
    question: '¿Cuál es el río más largo de África?',
    answers: ['Nilo', 'Congo', 'Níger', 'Zambeze'],
    correctAnswer: 'Nilo',
  },
  {
    level: 2,
    question: '¿Cuál es el lago más grande de África?',
    answers: ['Victoria', 'Tanganica', 'Albert', 'Malawi'],
    correctAnswer: 'Victoria',
  },
  {
    level: 2,
    question: '¿Cuál es el país más pequeño de Asia?',
    answers: ['Singapur', 'Mónaco', 'Brunéi', 'Maldivas'],
    correctAnswer: 'Singapur',
  },
  {
    level: 2,
    question: '¿Cuál es el desierto más grande del mundo?',
    answers: ['Sahara', 'Gobi', 'Kalahari', 'Arábigo'],
    correctAnswer: 'Sahara',
  },
  {
    level: 2,
    question: '¿Cuál es el país con más fronteras del mundo?',
    answers: ['Rusia', 'China', 'India', 'Brasil'],
    correctAnswer: 'China',
  },
  {
    level: 2,
    question: '¿Cuál es el país más pequeño del mundo?',
    answers: ['Mónaco', 'Nauru', 'Vaticano', 'Tuvalu'],
    correctAnswer: 'Vaticano',
  },
  {
    level: 2,
    question: '¿Cuál es el punto más bajo de la Tierra?',
    answers: ['Mar Muerto', 'Fosa de las Marianas', 'Depresión de Afar', 'Lago Assal'],
    correctAnswer: 'Mar Muerto',
  },
  {
    level: 2,
    question: '¿Cuál es el país más pequeño de Oceanía?',
    answers: ['Tuvalu', 'Nauru', 'Tonga', 'Fiyi'],
    correctAnswer: 'Nauru',
  },
  {
    level: 2,
    question: '¿Cuál es el punto más alto de África?',
    answers: ['Kilimanjaro', 'Monte Kenia', 'Ruwenzori', 'Sahara'],
    correctAnswer: 'Kilimanjaro',
  },
  {
    level: 3,
    question: '¿Cuál es el país más grande del mundo sin litoral?',
    answers: ['Bolivia', 'Zimbabue', 'Bután', 'Paraguay'],
    correctAnswer: 'Bolivia',
  },
  {
    level: 3,
    question: '¿Cuál es el país más pequeño de América del Sur?',
    answers: ['Surinam', 'Guyana', 'Uruguay', 'Surinam'],
    correctAnswer: 'Surinam',
  },
  {
    level: 3,
    question: '¿Cuál es el país más poblado de Europa?',
    answers: ['Rusia', 'Alemania', 'Francia', 'Reino Unido'],
    correctAnswer: 'Rusia',
  },
  {
    level: 3,
    question: '¿Cuál es el país más visitado del mundo?',
    answers: ['Francia', 'España', 'Estados Unidos', 'Italia'],
    correctAnswer: 'Francia',
  },
  {
    level: 3,
    question: '¿Cuál es el país más poblado de Asia?',
    answers: ['China', 'India', 'Indonesia', 'Pakistán'],
    correctAnswer: 'China',
  },
  {
    level: 3,
    question: '¿Cuál es el país más grande de América del Norte?',
    answers: ['Canadá', 'Estados Unidos', 'México', 'Groenlandia'],
    correctAnswer: 'Canadá',
  },
  {
    level: 3,
    question: '¿Cuál es el río más largo de Europa?',
    answers: ['Volga', 'Danubio', 'Rin', 'Támesis'],
    correctAnswer: 'Volga',
  },
  {
    level: 3,
    question: '¿Cuál es el país más poblado de África?',
    answers: ['Nigeria', 'Etiopía', 'Egipto', 'Sudáfrica'],
    correctAnswer: 'Nigeria',
  },
  {
    level: 3,
    question: '¿Cuál es el lago más grande del mundo?',
    answers: ['Caspian', 'Superior', 'Victoria', 'Baikal'],
    correctAnswer: 'Caspian',
  },
  {
    level: 3,
    question: '¿Cuál es el país más pequeño de Oceanía?',
    answers: ['Nauru', 'Tuvalu', 'Mónaco', 'San Marino'],
    correctAnswer: 'Nauru',
  },
  {
    level: 3,
    question: '¿Cuál es el río más largo de América del Sur?',
    answers: ['Amazonas', 'Paraná', 'Orinoco', 'Magdalena'],
    correctAnswer: 'Amazonas',
  },
  {
    level: 3,
    question: '¿Cuál es el país más grande de Oceanía?',
    answers: ['Australia', 'Nueva Zelanda', 'Papúa Nueva Guinea', 'Fiyi'],
    correctAnswer: 'Australia',
  },
  {
    level: 3,
    question: '¿Cuál es el país más poblado de América del Sur?',
    answers: ['Brasil', 'Argentina', 'Colombia', 'Perú'],
    correctAnswer: 'Brasil',
  },
  {
    level: 3,
    question: '¿Cuál es el océano más grande del mundo?',
    answers: ['Pacífico', 'Atlántico', 'Índico', 'Antártico'],
    correctAnswer: 'Pacífico',
  },
  {
    level: 3,
    question: '¿Cuál es el país más grande del mundo?',
    answers: ['Rusia', 'Canadá', 'China', 'Estados Unidos'],
    correctAnswer: 'Rusia',
  },
  {
    level: 4,
    question: '¿Cuál es el animal nacional de Australia?',
    answers: ['Canguro', 'Koala', 'Dingo', 'Emú'],
    correctAnswer: 'Canguro',
  },
  {
    level: 4,
    question: '¿Cuál es el animal nacional de Canadá?',
    answers: ['Castor', 'Oso polar', 'Lobo', 'Alce'],
    correctAnswer: 'Castor',
  },
  {
    level: 4,
    question: '¿Cuál es el animal nacional de Brasil?',
    answers: ['Jaguar', 'Tucán', 'Anaconda', 'Papagayo'],
    correctAnswer: 'Jaguar',
  },
  {
    level: 4,
    question: '¿Cuál es el animal nacional de China?',
    answers: ['Panda gigante', 'Dragón chino', 'Tigre siberiano', 'Leopardo de las nieves'],
    correctAnswer: 'Panda gigante',
  },
  {
    level: 4,
    question: '¿Cuál es el animal nacional de Sudáfrica?',
    answers: ['León', 'Elefante', 'Rinoceronte', 'Leopardo'],
    correctAnswer: 'León',
  },
  {
    level: 4,
    question: '¿Cuál es el animal nacional de India?',
    answers: ['Tigre de Bengala', 'Elefante indio', 'Leopardo de las nieves', 'León asiático'],
    correctAnswer: 'Tigre de Bengala',
  },
  {
    level: 4,
    question: '¿Cuál es el animal nacional de Estados Unidos?',
    answers: ['Águila calva', 'Bisonte americano', 'Oso pardo', 'Lobo gris'],
    correctAnswer: 'Águila calva',
  },
  {
    level: 4,
    question: '¿Cuál es el animal nacional de Rusia?',
    answers: ['Oso pardo', 'Lobo gris', 'Tigre siberiano', 'Leopardo de las nieves'],
    correctAnswer: 'Oso pardo',
  },
  {
    level: 4,
    question: '¿Cuál es el animal nacional de México?',
    answers: ['Águila real', 'Jaguar', 'Coyote', 'Tlacuache'],
    correctAnswer: 'Águila real',
  },
  {
    level: 4,
    question: '¿Cuál es el animal nacional de Japón?',
    answers: ['Grulla japonesa', 'Zorro japonés', 'Mono japonés', 'Carpas koi'],
    correctAnswer: 'Grulla japonesa',
  },
  {
    level: 4,
    question: '¿Cuál es la nacionalidad de Shakira?',
    answers: ['Colombiana', 'Mexicana', 'Española', 'Argentina'],
    correctAnswer: 'Colombiana',
  },
  {
    level: 4,
    question: '¿Cuál es la nacionalidad de Justin Bieber?',
    answers: ['Canadiense', 'Estadounidense', 'Británico', 'Australiano'],
    correctAnswer: 'Canadiense',
  },
  {
    level: 4,
    question: '¿Cuál es la nacionalidad de Adele?',
    answers: ['Británica', 'Estadounidense', 'Australiana', 'Canadiense'],
    correctAnswer: 'Británica',
  },
  {
    level: 4,
    question: '¿Cuál es la nacionalidad de Ricky Martin?',
    answers: ['Puertorriqueña', 'Mexicana', 'Española', 'Colombiana'],
    correctAnswer: 'Puertorriqueña',
  },
  {
    level: 4,
    question: '¿Cuál es la nacionalidad de Beyoncé?',
    answers: ['Estadounidense', 'Británica', 'Jamaicana', 'Nigeriana'],
    correctAnswer: 'Estadounidense',
  },
  {
    level: 5,
    question: '¿Cuál es la capital de Sudáfrica?',
    answers: ['Ciudad del Cabo', 'Johannesburgo', 'Pretoria', 'Durban'],
    correctAnswer: 'Pretoria',
  },
  {
    level: 5,
    question: '¿Cuál es la capital de India?',
    answers: ['Nueva Delhi', 'Bombay', 'Calcuta', 'Bangalore'],
    correctAnswer: 'Nueva Delhi',
  },
  {
    level: 5,
    question: '¿Cuál es la capital de Estados Unidos?',
    answers: ['Nueva York', 'Los Ángeles', 'Washington D.C.', 'Chicago'],
    correctAnswer: 'Washington D.C.',
  },
  {
    level: 5,
    question: '¿Cuál es la capital de Rusia?',
    answers: ['Moscú', 'San Petersburgo', 'Novosibirsk', 'Ekaterimburgo'],
    correctAnswer: 'Moscú',
  },
  {
    level: 5,
    question: '¿Cuál es la capital de México?',
    answers: ['Ciudad de México', 'Guadalajara', 'Monterrey', 'Puebla'],
    correctAnswer: 'Ciudad de México',
  },
  {
    level: 5,
    question: '¿Cuál es la capital de Japón?',
    answers: ['Tokio', 'Kioto', 'Osaka', 'Yokohama'],
    correctAnswer: 'Tokio',
  },
  {
    level: 5,
    question: '¿Cuál es el color de la bandera de Francia?',
    answers: ['Azul, blanco y rojo', 'Verde, blanco y rojo', 'Amarillo, azul y rojo', 'Blanco, rojo y verde'],
    correctAnswer: 'Azul, blanco y rojo',
  },
  {
    level: 5,
    question: '¿Cuál es el color de la bandera de Italia?',
    answers: ['Verde, blanco y rojo', 'Amarillo, azul y rojo', 'Blanco, rojo y verde', 'Verde, blanco y negro'],
    correctAnswer: 'Verde, blanco y rojo',
  },
  {
    level: 5,
    question: '¿Cuál es el color de la bandera de Alemania?',
    answers: ['Negro, rojo y amarillo', 'Verde, blanco y rojo', 'Blanco, rojo y verde', 'Amarillo, azul y rojo'],
    correctAnswer: 'Negro, rojo y amarillo',
  },
  {
    level: 5,
    question: '¿Cuál es el color de la bandera de España?',
    answers: ['Rojo y amarillo', 'Verde, blanco y rojo', 'Blanco, rojo y verde', 'Amarillo, azul y rojo'],
    correctAnswer: 'Rojo y amarillo',
  },
  {
    level: 5,
    question: '¿Cuál es el color de la bandera de Brasil?',
    answers: ['Verde y amarillo', 'Verde, blanco y rojo', 'Blanco, rojo y verde', 'Amarillo, azul y rojo'],
    correctAnswer: 'Verde y amarillo',
  },
  {
    level: 6,
    question: '¿Cuál es el estado más poblado de México?',
    answers: ['Ciudad de México', 'Estado de México', 'Jalisco', 'Veracruz'],
    correctAnswer: 'Estado de México',
  },
  {
    level: 6,
    question: '¿Cuál es el estado más pequeño de México?',
    answers: ['Tlaxcala', 'Colima', 'Aguascalientes', 'Baja California Sur'],
    correctAnswer: 'Tlaxcala',
  },
  {
    level: 6,
    question: '¿Cuál es la provincia más grande de Canadá?',
    answers: ['Quebec', 'Ontario', 'Alberta', 'Columbia Británica'],
    correctAnswer: 'Quebec',
  },
  {
    level: 6,
    question: '¿Cuál es la provincia más poblada de Canadá?',
    answers: ['Ontario', 'Quebec', 'Alberta', 'Columbia Británica'],
    correctAnswer: 'Ontario',
  },
  {
    level: 6,
    question: '¿Cuál es la provincia más pequeña de Canadá?',
    answers: ['Príncipe Eduardo', 'Nueva Escocia', 'Nueva Brunswick', 'Terranova y Labrador'],
    correctAnswer: 'Príncipe Eduardo',
  },
  {
    level: 6,
    question: '¿Cuál es la provincia más grande de Australia?',
    answers: ['Queensland', 'Nueva Gales del Sur', 'Australia Occidental', 'Australia Meridional'],
    correctAnswer: 'Australia Occidental',
  },
  {
    level: 6,
    question: '¿Cuál es la provincia más poblada de Australia?',
    answers: ['Nueva Gales del Sur', 'Victoria', 'Queensland', 'Australia Occidental'],
    correctAnswer: 'Nueva Gales del Sur',
  },
  {
    level: 6,
    question: '¿Cuál es la provincia más pequeña de Australia?',
    answers: ['Tasmania', 'Territorio del Norte', 'Australia Meridional', 'Queensland'],
    correctAnswer: 'Tasmania',
  },
  {
    level: 6,
    question: '¿Quién es el presidente de Estados Unidos?',
    answers: ['Joe Biden', 'Donald Trump', 'Barack Obama', 'George W. Bush'],
    correctAnswer: 'Joe Biden',
  },
  {
    level: 6,
    question: '¿Quién es el presidente de Rusia?',
    answers: ['Vladimir Putin', 'Dmitry Medvedev', 'Boris Yeltsin', 'Mikhail Gorbachev'],
    correctAnswer: 'Vladimir Putin',
  },
  {
    level: 6,
    question: '¿Quién es el presidente de China?',
    answers: ['Xi Jinping', 'Hu Jintao', 'Jiang Zemin', 'Deng Xiaoping'],
    correctAnswer: 'Xi Jinping',
  },
  {
    level: 6,
    question: '¿Quién es el presidente de Brasil?',
    answers: ['Jair Bolsonaro', 'Michel Temer', 'Dilma Rousseff', 'Luiz Inácio Lula da Silva'],
    correctAnswer: 'Jair Bolsonaro',
  },
  {
    level: 6,
    question: '¿Quién es el presidente de México?',
    answers: ['Andrés Manuel López Obrador', 'Enrique Peña Nieto', 'Felipe Calderón', 'Vicente Fox'],
    correctAnswer: 'Andrés Manuel López Obrador',
  }

];
