export const triviaData = [
  {
    level: 1,
    question: '¿Cuál es la capital de Francia?',
    answers: ['Roma', 'París', 'Londres', 'Madrid'],
    correctAnswer: 'París',
  },
  {
    level: 1,
    question: '¿Cuál es el océano más grande del mundo?',
    answers: ['Atlántico', 'Índico', 'Pacífico', 'Ártico'],
    correctAnswer: 'Pacífico',
  },
  {
    level: 1,
    question: '¿Cuál es el país más grande del mundo?',
    answers: ['Canadá', 'China', 'Rusia', 'Estados Unidos'],
    correctAnswer: 'Rusia',
  },
  {
    level: 1,
    question: '¿Cuál es el río más largo de Europa?',
    answers: ['Rin', 'Danubio', 'Volga', 'Loira'],
    correctAnswer: 'Volga',
  },
  {
    level: 1,
    question: '¿Cuál es el continente más grande del mundo?',
    answers: ['América', 'África', 'Asia', 'Europa'],
    correctAnswer: 'Asia',
  },
  {
    level: 1,
    question: '¿Cuál es el país más grande de América del Sur?',
    answers: ['chile', 'Argentina', 'Colombia', 'Brasil'],
    correctAnswer: 'Brasil',
  },
  {
    level: 1,
    question: '¿Cuál es el animal terrestre más grande del mundo?',
    answers: ['Rinoceronte', 'Jirafa', 'Hipopótamo', 'Elefante'],
    correctAnswer: 'Elefante',
  },
  {
    level: 1,
    question: '¿Cuál es el océano más pequeño del mundo?',
    answers: ['Ártico', 'Índico', 'Atlántico', 'Pacífico'],
    correctAnswer: 'Ártico',
  },
  {
    level: 1,
    question: '¿Cuál es el país más visitado del mundo?',
    answers: ['Italia', 'España', 'Francia', 'Estados Unidos'],
    correctAnswer: 'Francia',
  },
  {
    level: 1,
    question: '¿Cuál es el lago más profundo del mundo?',
    answers: ['Baikal', 'Superior', 'Victoria', 'Tanganica'],
    correctAnswer: 'Baikal',
  },
  {
    level: 1,
    question: '¿Cuál es el país más pequeño de América?',
    answers: [
      'San Cristóbal y Nieves',
      'Antigua y Barbuda',
      'Barbados',
      'Granada',
    ],
    correctAnswer: 'San Cristóbal y Nieves',
  },
  {
    level: 1,
    question: '¿Cuál es el continente con más países?',
    answers: ['África', 'Asia', 'Europa', 'América'],
    correctAnswer: 'África',
  },
  {
    level: 1,
    question: '¿Cuál es el país más poblado de Europa?',
    answers: ['Francia', 'Alemania', 'Rusia', 'Reino Unido'],
    correctAnswer: 'Rusia',
  },
  {
    level: 1,
    question: '¿Cuál es el río más largo de América?',
    answers: ['Amazonas', 'Misisipi', 'Yukón', 'Paraná'],
    correctAnswer: 'Amazonas',
  },
  {
    level: 1,
    question: '¿Cuál es el continente donde se encuentra Egipto?',
    answers: ['Asia', 'África', 'Europa', 'Oceanía'],
    correctAnswer: 'África',
  },
  {
    level: 2,
    question: '¿Cuál es el país más grande de América del Norte?',
    answers: ['Estados Unidos', 'Canadá', 'México', 'Cuba'],
    correctAnswer: 'Canadá',
  },
  {
    level: 2,
    question: '¿Cuál es el lago más grande de América del Norte?',
    answers: ['Superior', 'Michigan', 'Huron', 'Erie'],
    correctAnswer: 'Superior',
  },
  {
    level: 2,
    question: '¿Cuál es el país más poblado de América del Sur?',
    answers: ['Brasil', 'Argentina', 'Colombia', 'Perú'],
    correctAnswer: 'Brasil',
  },
  {
    level: 2,
    question: '¿Cuál es el río más largo de América del Sur?',
    answers: ['Orinoco', 'Paraná', 'Amazonas', 'Magdalena'],
    correctAnswer: 'Amazonas',
  },
  {
    level: 2,
    question: '¿Cuál es el país más visitado de América del Norte?',
    answers: ['Estados Unidos', 'Canadá', 'México', 'Cuba'],
    correctAnswer: 'Estados Unidos',
  },
  {
    level: 2,
    question: '¿Cuál es el país más pequeño de Europa?',
    answers: ['Mónaco', 'Vaticano', 'San Marino', 'Liechtenstein'],
    correctAnswer: 'Vaticano',
  },
  {
    level: 2,
    question: '¿Cuál es el país más poblado de África?',
    answers: ['Nigeria', 'Etiopía', 'Egipto', 'Sudáfrica'],
    correctAnswer: 'Nigeria',
  },
  {
    level: 2,
    question: '¿Cuál es el país más grande de Oceanía?',
    answers: ['Fiyi', 'Nueva Zelanda', 'Papúa Nueva Guinea', 'Australia'],
    correctAnswer: 'Australia',
  },
  {
    level: 2,
    question: '¿Cuál es el río más largo de Asia?',
    answers: ['Ganges', 'Misisipi', 'Ganges', 'Yangtsé'],
    correctAnswer: 'Yangtsé',
  },
  {
    level: 2,
    question: '¿Cuál es el país más poblado del mundo?',
    answers: ['India', 'China', 'Estados Unidos', 'Indonesia'],
    correctAnswer: 'China',
  },
  {
    level: 2,
    question: '¿Cuál es la montaña más alta del mundo?',
    answers: ['K2', 'Everest', 'Kangchenjunga', 'Lhotse'],
    correctAnswer: 'Everest',
  },
  {
    level: 2,
    question: '¿Cuál es el lago más alto del mundo?',
    answers: ['Titicaca', 'Baikal', 'Maracaibo', 'Vostok'],
    correctAnswer: 'Titicaca',
  },
  {
    level: 2,
    question: '¿Cuál es el país con más islas del mundo?',
    answers: ['Filipinas', 'Indonesia', 'Japón', 'Reino Unido'],
    correctAnswer: 'Indonesia',
  },
  {
    level: 2,
    question: '¿Cuál es el río más largo de África?',
    answers: ['Níger', 'Congo', 'Nilo', 'Zambeze'],
    correctAnswer: 'Nilo',
  },
  {
    level: 2,
    question: '¿Cuál es el lago más grande de África?',
    answers: ['Victoria', 'Tanganica', 'Albert', 'Malawi'],
    correctAnswer: 'Victoria',
  },
  {
    level: 2,
    question: '¿Cuál es el país más pequeño de Asia?',
    answers: ['Maldivas', 'Mónaco', 'Brunéi', 'Singapur'],
    correctAnswer: 'Singapur',
  },
  {
    level: 2,
    question: '¿Cuál es el desierto más grande del mundo?',
    answers: ['Sahara', 'Gobi', 'Kalahari', 'Arábigo'],
    correctAnswer: 'Sahara',
  },
  {
    level: 2,
    question: '¿Cuál es el país con más fronteras del mundo?',
    answers: ['Rusia', 'China', 'India', 'Brasil'],
    correctAnswer: 'China',
  },
  {
    level: 2,
    question: '¿Cuál es el país más pequeño del mundo?',
    answers: ['Mónaco', 'Nauru', 'Vaticano', 'Tuvalu'],
    correctAnswer: 'Vaticano',
  },
  {
    level: 2,
    question: '¿Cuál es el punto más bajo de la Tierra?',
    answers: [
      'Mar Muerto',
      'Fosa de las Marianas',
      'Depresión de Afar',
      'Lago Assal',
    ],
    correctAnswer: 'Mar Muerto',
  },
  {
    level: 2,
    question: '¿Cuál es el país más pequeño de Oceanía?',
    answers: ['Tuvalu', 'Nauru', 'Tonga', 'Fiyi'],
    correctAnswer: 'Nauru',
  },
  {
    level: 2,
    question: '¿Cuál es el punto más alto de África?',
    answers: ['Kilimanjaro', 'Monte Kenia', 'Ruwenzori', 'Sahara'],
    correctAnswer: 'Kilimanjaro',
  },
  {
    level: 3,
    question: '¿Cuál es el país más grande del mundo sin litoral?',
    answers: ['Bolivia', 'Zimbabue', 'Bután', 'Paraguay'],
    correctAnswer: 'Bolivia',
  },
  {
    level: 3,
    question: '¿Cuál es el país más pequeño de América del Sur?',
    answers: ['Surinam', 'Guyana', 'Uruguay', 'Surinam'],
    correctAnswer: 'Surinam',
  },
  {
    level: 3,
    question: '¿Cuál es el país más poblado de Europa?',
    answers: ['Rusia', 'Alemania', 'Francia', 'Reino Unido'],
    correctAnswer: 'Rusia',
  },
  {
    level: 3,
    question: '¿Cuál es el país más visitado del mundo?',
    answers: ['España', 'Francia', 'Estados Unidos', 'Italia'],
    correctAnswer: 'Francia',
  },
  {
    level: 3,
    question: '¿Cuál es el país más poblado de Asia?',
    answers: ['India', 'China', 'Indonesia', 'Pakistán'],
    correctAnswer: 'China',
  },
  {
    level: 3,
    question: '¿Cuál es el país más grande de América del Norte?',
    answers: ['México', 'Estados Unidos', 'Canadá', 'Groenlandia'],
    correctAnswer: 'Canadá',
  },
  {
    level: 3,
    question: '¿Cuál es el río más largo de Europa?',
    answers: ['Rin', 'Danubio', 'Volga', 'Támesis'],
    correctAnswer: 'Volga',
  },
  {
    level: 3,
    question: '¿Cuál es el país más poblado de África?',
    answers: ['Nigeria', 'Etiopía', 'Egipto', 'Sudáfrica'],
    correctAnswer: 'Nigeria',
  },
  {
    level: 3,
    question: '¿Cuál es el lago más grande del mundo?',
    answers: ['Victoria', 'Superior', 'Caspian', 'Baikal'],
    correctAnswer: 'Caspian',
  },
  {
    level: 3,
    question: '¿Cuál es el país más pequeño de Oceanía?',
    answers: ['Nauru', 'Tuvalu', 'Mónaco', 'San Marino'],
    correctAnswer: 'Nauru',
  },
  {
    level: 3,
    question: '¿Cuál es el río más largo de América del Sur?',
    answers: ['Paraná', 'Magdalena', 'Amazonas', 'Orinoco'],
    correctAnswer: 'Amazonas',
  },
  {
    level: 3,
    question: '¿Cuál es el país más grande de Oceanía?',
    answers: ['Fiyi', 'Nueva Zelanda', 'Australia', 'Papúa Nueva Guinea'],
    correctAnswer: 'Australia',
  },
  {
    level: 3,
    question: '¿Cuál es el país más poblado de América del Sur?',
    answers: ['Argentina', 'Perú', 'Brasil', 'Colombia'],
    correctAnswer: 'Brasil',
  },
  {
    level: 3,
    question: '¿Cuál es el océano más grande del mundo?',
    answers: ['Antártico', 'Índico', 'Atlántico', 'Pacífico'],
    correctAnswer: 'Pacífico',
  },
  {
    level: 3,
    question: '¿Cuál es el país más grande del mundo?',
    answers: ['Estados Unidos', 'Canadá', 'China', 'Rusia'],
    correctAnswer: 'Rusia',
  },
  {
    level: 4,
    question: '¿Cuál es el animal nacional de Australia?',
    answers: ['Koala', 'Dingo', 'Emú', 'Canguro'],
    correctAnswer: 'Canguro',
  },
  {
    level: 4,
    question: '¿Cuál es el animal nacional de Canadá?',
    answers: ['Alce', 'Oso polar', 'Castor', 'Lobo'],
    correctAnswer: 'Castor',
  },
  {
    level: 4,
    question: '¿Cuál es el animal nacional de Brasil?',
    answers: ['Anaconda', 'Tucán', 'Papagayo', 'Jaguar'],
    correctAnswer: 'Jaguar',
  },
  {
    level: 4,
    question: '¿Cuál es el animal nacional de China?',
    answers: [
      'Leopardo de las nieves',
      'Tigre siberiano',
      'Dragón chino',
      'Panda gigante',
    ],
    correctAnswer: 'Panda gigante',
  },
  {
    level: 4,
    question: '¿Cuál es el animal nacional de Sudáfrica?',
    answers: ['Rinoceronte', 'León', 'Elefante', 'Leopardo'],
    correctAnswer: 'León',
  },
  {
    level: 4,
    question: '¿Cuál es el animal nacional de India?',
    answers: [
      'Tigre de Bengala',
      'León asiático',
      'Leopardo de las nieves',
      'Elefante indio',
    ],
    correctAnswer: 'Tigre de Bengala',
  },
  {
    level: 4,
    question: '¿Cuál es el animal nacional de Estados Unidos?',
    answers: ['Oso pardo', 'Águila calva', 'Bisonte americano', 'Lobo gris'],
    correctAnswer: 'Águila calva',
  },
  {
    level: 4,
    question: '¿Cuál es el animal nacional de Rusia?',
    answers: [
      'Tigre siberiano',
      'Oso pardo',
      'Leopardo de las nieves',
      'Lobo gris',
    ],
    correctAnswer: 'Oso pardo',
  },
  {
    level: 4,
    question: '¿Cuál es el animal nacional de México?',
    answers: ['Coyote', 'Águila real', 'Jaguar', 'Tlacuache'],
    correctAnswer: 'Águila real',
  },
  {
    level: 4,
    question: '¿Cuál es el animal nacional de Japón?',
    answers: ['Mono japonés', 'Grulla japonesa', 'Carpas koi', 'Zorro japonés'],
    correctAnswer: 'Grulla japonesa',
  },
  {
    level: 4,
    question: '¿Cuál es la nacionalidad de Shakira?',
    answers: ['Colombiana', 'Española', 'Mexicana', 'Argentina'],
    correctAnswer: 'Colombiana',
  },
  {
    level: 4,
    question: '¿Cuál es la nacionalidad de Justin Bieber?',
    answers: ['Británico', 'Canadiense', 'Estadounidense', 'Australiano'],
    correctAnswer: 'Canadiense',
  },
  {
    level: 4,
    question: '¿Cuál es la nacionalidad de Adele?',
    answers: ['Estadounidense', 'Australiana', 'Canadiense', 'Británica'],
    correctAnswer: 'Británica',
  },
  {
    level: 4,
    question: '¿Cuál es la nacionalidad de Ricky Martin?',
    answers: ['Española', 'Mexicana', 'Puertorriqueña', 'Colombiana'],
    correctAnswer: 'Puertorriqueña',
  },
  {
    level: 4,
    question: '¿Cuál es la nacionalidad de Beyoncé?',
    answers: ['Jamaicana', 'Estadounidense', 'Británica', 'Nigeriana'],
    correctAnswer: 'Estadounidense',
  },
  {
    level: 5,
    question: '¿Cuál es la capital de Sudáfrica?',
    answers: ['Durban', 'Pretoria', 'Johannesburgo', 'Ciudad del Cabo'],
    correctAnswer: 'Pretoria',
  },
  {
    level: 5,
    question: '¿Cuál es la capital de India?',
    answers: ['Bangalore', 'Bombay', 'Nueva Delhi', 'Calcuta'],
    correctAnswer: 'Nueva Delhi',
  },
  {
    level: 5,
    question: '¿Cuál es la capital de Estados Unidos?',
    answers: ['Nueva York', 'Los Ángeles', 'Washington D.C.', 'Chicago'],
    correctAnswer: 'Washington D.C.',
  },
  {
    level: 5,
    question: '¿Cuál es la capital de Rusia?',
    answers: ['Ekaterimburgo', 'San Petersburgo', 'Moscú', 'Novosibirsk'],
    correctAnswer: 'Moscú',
  },
  {
    level: 5,
    question: '¿Cuál es la capital de México?',
    answers: ['Monterrey', 'Guadalajara', 'Puebla', 'Ciudad de México'],
    correctAnswer: 'Ciudad de México',
  },
  {
    level: 5,
    question: '¿Cuál es la capital de Japón?',
    answers: ['Yokohama', 'Osaka', 'Kioto', 'Tokio'],
    correctAnswer: 'Tokio',
  },
  {
    level: 5,
    question: '¿Cuál es el color de la bandera de Francia?',
    answers: [
      'Blanco, rojo y verde',
      'Amarillo, azul y rojo',
      'Verde, blanco y rojo',
      'Azul, blanco y rojo',
    ],
    correctAnswer: 'Azul, blanco y rojo',
  },
  {
    level: 5,
    question: '¿Cuál es el color de la bandera de Italia?',
    answers: [
      'Verde, blanco y negro',
      'Blanco, rojo y verde',
      'Amarillo, azul y rojo',
      'Verde, blanco y rojo',
    ],
    correctAnswer: 'Verde, blanco y rojo',
  },
  {
    level: 5,
    question: '¿Cuál es el color de la bandera de Alemania?',
    answers: [
      'Amarillo, azul y rojo',
      'Negro, rojo y amarillo',
      'Blanco, rojo y verde',
      'Verde, blanco y rojo',
    ],
    correctAnswer: 'Negro, rojo y amarillo',
  },
  {
    level: 5,
    question: '¿Cuál es el color de la bandera de España?',
    answers: [
      'Blanco, rojo y verde',
      'Rojo y amarillo',
      'Verde, blanco y rojo',
      'Amarillo, azul y rojo',
    ],
    correctAnswer: 'Rojo y amarillo',
  },
  {
    level: 5,
    question: '¿Cuál es el color de la bandera de Brasil?',
    answers: [
      'Verde, blanco y rojo',
      'Verde y amarillo',
      'Blanco, rojo y verde',
      'Amarillo, azul y rojo',
    ],
    correctAnswer: 'Verde y amarillo',
  },
  {
    level: 6,
    question: '¿Cuál es el estado más poblado de México?',
    answers: ['Veracruz', 'Ciudad de México', 'Jalisco', 'Estado de México'],
    correctAnswer: 'Estado de México',
  },
  {
    level: 6,
    question: '¿Cuál es el estado más pequeño de México?',
    answers: ['Aguascalientes', 'Tlaxcala', 'Colima', 'Baja California Sur'],
    correctAnswer: 'Tlaxcala',
  },
  {
    level: 6,
    question: '¿Cuál es la provincia más grande de Canadá?',
    answers: ['Columbia Británica', 'Alberta', 'Ontario', 'Quebec'],
    correctAnswer: 'Quebec',
  },
  {
    level: 6,
    question: '¿Cuál es la provincia más poblada de Canadá?',
    answers: ['Alberta', 'Ontario', 'Quebec', 'Columbia Británica'],
    correctAnswer: 'Ontario',
  },
  {
    level: 6,
    question: '¿Cuál es la provincia más pequeña de Canadá?',
    answers: [
      'Nueva Brunswick',
      'Nueva Escocia',
      'Terranova y Labrador',
      'Príncipe Eduardo',
    ],
    correctAnswer: 'Príncipe Eduardo',
  },
  {
    level: 6,
    question: '¿Cuál es la provincia más grande de Australia?',
    answers: [
      'Australia Occidental',
      'Australia Meridional',
      'Queensland',
      'Nueva Gales del Sur',
    ],
    correctAnswer: 'Australia Occidental',
  },
  {
    level: 6,
    question: '¿Cuál es la provincia más poblada de Australia?',
    answers: [
      'Victoria',
      'Australia Occidental',
      'Queensland',
      'Nueva Gales del Sur',
    ],
    correctAnswer: 'Nueva Gales del Sur',
  },
  {
    level: 6,
    question: '¿Cuál es la provincia más pequeña de Australia?',
    answers: [
      'Queensland',
      'Tasmania',
      'Australia Meridional',
      'Territorio del Norte',
    ],
    correctAnswer: 'Tasmania',
  },
  {
    level: 6,
    question: '¿Quién es el presidente de Estados Unidos?',
    answers: ['Donald Trump', 'Joe Biden', 'Barack Obama', 'George W. Bush'],
    correctAnswer: 'Joe Biden',
  },
  {
    level: 6,
    question: '¿Quién es el presidente de Rusia?',
    answers: [
      'Dmitry Medvedev',
      'Mikhail Gorbachev',
      'Boris Yeltsin',
      'Vladimir Putin',
    ],
    correctAnswer: 'Vladimir Putin',
  },
  {
    level: 6,
    question: '¿Quién es el presidente de China?',
    answers: ['Hu Jintao', 'Deng Xiaoping', 'Xi Jinping', 'Jiang Zemin'],
    correctAnswer: 'Xi Jinping',
  },
  {
    level: 6,
    question: '¿Quién es el presidente de Brasil?',
    answers: [
      'Michel Temer',
      'Luiz Inácio Lula da Silva',
      'Jair Bolsonaro',
      'Dilma Rousseff',
    ],
    correctAnswer: 'Jair Bolsonaro',
  },
  {
    level: 6,
    question: '¿Quién es el presidente de México?',
    answers: [
      'Felipe Calderón',
      'Andrés Manuel López Obrador',
      'Vicente Fox',
      'Enrique Peña Nieto',
    ],
    correctAnswer: 'Andrés Manuel López Obrador',
  },
];
